phraseapp:
  access_token: 4d9b2a857bd20dc381b4b383825377c8fdec6bd05f60accce167c01a461744ce
  project_id: 50902f1527d40887fdc6ffa305b894e7
  push:
    sources:
    - file: ./assets/key.json
      params:
        file_format: json
  pull:
    targets:
    - file: ./assets/es.json
      params:
        file_format: json
    - file: ./assets/fr.json
      params:
        file_format: json
    - file: ./assets/cz.json
      params:
        file_format: json
    - file: ./assets/it.json
      params:
        file_format: json
    - file: ./assets/en.json
      params:
        file_format: json
